version: "3.9"
services:
  mysql:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bootdb
    ports:
      - "3306:3306"
      - "33060:33060"

  cache:
    image: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - cache:/data

  stock-manager:
    image: adautomendes/stock-manager
    ports:
      - "8080:8080"
    environment:
      - SERVER_HOST=stock-manager
      - SERVER_PORT=8080
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
      - SPRING_PROFILES_ACTIVE=prod
    depends_on:
      mysql:
        condition: service_started

  quotations-management:
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - "8081:8081"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/bootdb
      - SPRING_PROFILES_ACTIVE=prod
      - MYSQL_USERNAME=root
      - MYSQL_PASSWORD=root
    depends_on:
      stock-manager:
        condition: service_started
      mysql:
        condition: service_started
      cache:
        condition: service_started


volumes:
  cache:
    driver: local
